package com.pfe.localisation.object;



// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

/**
 * Arrete generated by hbm2java
 */
public class Arrete implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5158088559320288883L;
	private int idarrete;
	private NoeudNav noeudNavByIdsource;
	private NoeudNav noeudNavByIddistination;
	private double cout;

	public Arrete() {
	}

	public Arrete(int idarrete, NoeudNav noeudNavByIdsource,
			NoeudNav noeudNavByIddistination, double cout) {
		this.idarrete = idarrete;
		this.noeudNavByIdsource = noeudNavByIdsource;
		this.noeudNavByIddistination = noeudNavByIddistination;
		this.cout = cout;
	}

	public int getIdarrete() {
		return this.idarrete;
	}

	public void setIdarrete(int idarrete) {
		this.idarrete = idarrete;
	}
	@org.codehaus.jackson.annotate.JsonIgnore
	public NoeudNav getNoeudNavByIdsource() {
		return this.noeudNavByIdsource;
	}

	public void setNoeudNavByIdsource(NoeudNav noeudNavByIdsource) {
		this.noeudNavByIdsource = noeudNavByIdsource;
	}
	@org.codehaus.jackson.annotate.JsonIgnore
	public NoeudNav getNoeudNavByIddistination() {
		return this.noeudNavByIddistination;
	}

	public void setNoeudNavByIddistination(NoeudNav noeudNavByIddistination) {
		this.noeudNavByIddistination = noeudNavByIddistination;
	}

	public double getCout() {
		return this.cout;
	}

	public void setCout(double cout) {
		this.cout = cout;
	}

}
