package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Batiment generated by hbm2java
 */
public class Batiment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7490936784763159705L;
	private int idbatiment;
	private int numbatiment;
	private String nombatiment;
	private String adresse;
	private String ville;
	private Set<Etage> etages = new HashSet<Etage>(0);

	public Batiment() {
	}

	public Batiment(int idbatiment, int numbatiment, String adresse) {
		this.idbatiment = idbatiment;
		this.numbatiment = numbatiment;
		this.adresse = adresse;
	}

	public Batiment(int idbatiment, int numbatiment, String nombatiment,
			String adresse, String ville, Set<Etage> etages) {
		this.idbatiment = idbatiment;
		this.numbatiment = numbatiment;
		this.nombatiment = nombatiment;
		this.adresse = adresse;
		this.ville = ville;
		this.etages = etages;
	}

	public int getIdbatiment() {
		return this.idbatiment;
	}

	public void setIdbatiment(int idbatiment) {
		this.idbatiment = idbatiment;
	}

	public int getNumbatiment() {
		return this.numbatiment;
	}

	public void setNumbatiment(int numbatiment) {
		this.numbatiment = numbatiment;
	}

	public String getNombatiment() {
		return this.nombatiment;
	}

	public void setNombatiment(String nombatiment) {
		this.nombatiment = nombatiment;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set<Etage> getEtages() {
		return this.etages;
	}

	public void setEtages(Set<Etage> etages) {
		this.etages = etages;
	}

}
