package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;



/**
 * Commentaire generated by hbm2java
 */
public class Commentaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5015758982393972854L;
	private int idcommentaire;
	private Utilisateur utilisateur;
	private String textcommentaire;
	private Date datecommainte;

	public Commentaire() {
	}

	public Commentaire(int idcommentaire, Utilisateur utilisateur,
			String textcommentaire, Date datecommainte) {
		this.idcommentaire = idcommentaire;
		this.utilisateur = utilisateur;
		this.textcommentaire = textcommentaire;
		this.datecommainte = datecommainte;
	}

	public int getIdcommentaire() {
		return this.idcommentaire;
	}

	public void setIdcommentaire(int idcommentaire) {
		this.idcommentaire = idcommentaire;
	}
	@JsonIgnore
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getTextcommentaire() {
		return this.textcommentaire;
	}

	public void setTextcommentaire(String textcommentaire) {
		this.textcommentaire = textcommentaire;
	}

	public Date getDatecommainte() {
		return this.datecommainte;
	}

	public void setDatecommainte(Date datecommainte) {
		this.datecommainte = datecommainte;
	}

}
