package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonIgnore;

import com.vividsolutions.jts.geom.Point;

/**
 * Fingerprints generated by hbm2java
 */
public class Fingerprints implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idfingerprints;
	private Indoorspace indoorspace;
	private Point position;
	private Set<Rssi> rssis = new HashSet<Rssi>(0);

	public Fingerprints() {
	}

	public Fingerprints(int idfingerprints, Indoorspace indoorspace,
			Point position) {
		this.idfingerprints = idfingerprints;
		this.indoorspace = indoorspace;
		this.position = position;
	}

	public Fingerprints(int idfingerprints, Indoorspace indoorspace,
			Point position, Set<Rssi> rssis) {
		this.idfingerprints = idfingerprints;
		this.indoorspace = indoorspace;
		this.position = position;
		this.rssis = rssis;
	}

	public int getIdfingerprints() {
		return this.idfingerprints;
	}

	public void setIdfingerprints(int idfingerprints) {
		this.idfingerprints = idfingerprints;
	}
	@JsonIgnore
	public Indoorspace getIndoorspace() {
		return this.indoorspace;
	}

	public void setIndoorspace(Indoorspace indoorspace) {
		this.indoorspace = indoorspace;
	}
	
	public Point getPosition() {
		return this.position;
	}

	public void setPosition(Point position) {
		this.position = position;
	}

	@JsonIgnore
	public Set<Rssi> getRssis() {
		return this.rssis;
	}

	public void setRssis(Set<Rssi> rssis) {
		this.rssis = rssis;
	}

}
