package com.pfe.localisation.object;

import com.fasterxml.jackson.annotation.JsonIgnore;



// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

/**
 * HistoriqueLocalisation generated by hbm2java
 */
public class HistoriqueLocalisation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3668573343561710502L;
	private HistoriqueLocalisationId id;
	private Utilisateur utilisateur;

	public HistoriqueLocalisation() {
	}

	public HistoriqueLocalisation(HistoriqueLocalisationId id,
			Utilisateur utilisateur) {
		this.id = id;
		this.utilisateur = utilisateur;
	}

	@JsonIgnore
	public HistoriqueLocalisationId getId() {
		return this.id;
	}

	public void setId(HistoriqueLocalisationId id) {
		this.id = id;
	}

	@JsonIgnore
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

}
