package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

/**
 * HistoriqueLocalisationId generated by hbm2java
 */
public class HistoriqueLocalisationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8316750071979561723L;
	private int idutilisateur;
	private int idfingerprints;

	public HistoriqueLocalisationId() {
	}

	public HistoriqueLocalisationId(int idutilisateur, int idfingerprints) {
		this.idutilisateur = idutilisateur;
		this.idfingerprints = idfingerprints;
	}

	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public int getIdfingerprints() {
		return this.idfingerprints;
	}

	public void setIdfingerprints(int idfingerprints) {
		this.idfingerprints = idfingerprints;
	}

	

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdutilisateur();
		result = 37 * result + this.getIdfingerprints();
		return result;
	}

}
