package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonIgnore;
/**
 * NoeudNav generated by hbm2java
 */
public class NoeudNav implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2458864432718608120L;
	private double noeudid;
	private Indoorspace indoorspace;
	private Serializable geom;
	private Set<Arrete> arretesForIddistination = new HashSet<Arrete>(0);
	private Set<Arrete> arretesForIdsource = new HashSet<Arrete>(0);

	public NoeudNav() {
	}

	public NoeudNav(double noeudid) {
		this.noeudid = noeudid;
	}

	public NoeudNav(double noeudid, Indoorspace indoorspace, Serializable geom,
			Set<Arrete> arretesForIddistination, Set<Arrete> arretesForIdsource) {
		this.noeudid = noeudid;
		this.indoorspace = indoorspace;
		this.geom = geom;
		this.arretesForIddistination = arretesForIddistination;
		this.arretesForIdsource = arretesForIdsource;
	}

	public double getNoeudid() {
		return this.noeudid;
	}

	public void setNoeudid(double noeudid) {
		this.noeudid = noeudid;
	}

	@JsonIgnore
	public Indoorspace getIndoorspace() {
		return this.indoorspace;
	}

	public void setIndoorspace(Indoorspace indoorspace) {
		this.indoorspace = indoorspace;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

	public Set<Arrete> getArretesForIddistination() {
		return this.arretesForIddistination;
	}

	public void setArretesForIddistination(Set<Arrete> arretesForIddistination) {
		this.arretesForIddistination = arretesForIddistination;
	}

	public Set<Arrete> getArretesForIdsource() {
		return this.arretesForIdsource;
	}

	public void setArretesForIdsource(Set<Arrete> arretesForIdsource) {
		this.arretesForIdsource = arretesForIdsource;
	}

}
