package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Object generated by hbm2java
 */
public class Object implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1762767023718979937L;
	private BigDecimal objectid;
	private Indoorspace indoorspace;
	private int gid;
	private String objtype;
	private Serializable geom;

	public Object() {
	}

	public Object(BigDecimal objectid, int gid) {
		this.objectid = objectid;
		this.gid = gid;
	}

	public Object(BigDecimal objectid, Indoorspace indoorspace, int gid,
			String objtype, Serializable geom) {
		this.objectid = objectid;
		this.indoorspace = indoorspace;
		this.gid = gid;
		this.objtype = objtype;
		this.geom = geom;
	}

	public BigDecimal getObjectid() {
		return this.objectid;
	}

	public void setObjectid(BigDecimal objectid) {
		this.objectid = objectid;
	}

	@JsonIgnore
	public Indoorspace getIndoorspace() {
		return this.indoorspace;
	}

	public void setIndoorspace(Indoorspace indoorspace) {
		this.indoorspace = indoorspace;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getObjtype() {
		return this.objtype;
	}

	public void setObjtype(String objtype) {
		this.objtype = objtype;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

}
