package com.pfe.localisation.object;


import java.util.HashSet;
import java.util.Set;

/**
 * Pointacces generated by hbm2java
 */
public class Pointacces implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2072511325030830764L;
	private int idpointacces;
	private String apName;
	private String adressemac;
	private Set<Rssi> rssis = new HashSet<Rssi>(0);
	

	public Pointacces() {
	}

	
	public String getApName() {
		return apName;
	}


	public void setApName(String apName) {
		this.apName = apName;
	}


	public Pointacces(int idpointacces, String adressemac) {
		this.idpointacces = idpointacces;
		this.adressemac = adressemac;
	}

	public Pointacces(int idpointacces, String adressemac, Set<Rssi> rssis) {
		this.idpointacces = idpointacces;
		this.adressemac = adressemac;
		this.rssis = rssis;
	}

	public int getIdpointacces() {
		return this.idpointacces;
	}

	public void setIdpointacces(int idpointacces) {
		this.idpointacces = idpointacces;
	}

	public String getAdressemac() {
		return this.adressemac;
	}

	public void setAdressemac(String adressemac) {
		this.adressemac = adressemac;
	}

		public Set<Rssi> getRssis() {
		return this.rssis;
	}

	public void setRssis(Set<Rssi> rssis) {
		this.rssis = rssis;
	}

}
