package com.pfe.localisation.object;

// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

/**
 * RssiId generated by hbm2java
 */
public class RssiId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2111460427152436576L;
	private int idpointacces;
	private int idfingerprints;

	public RssiId() {
	}

	public RssiId(int idpointacces, int idfingerprints) {
		this.idpointacces = idpointacces;
		this.idfingerprints = idfingerprints;
	}

	public int getIdpointacces() {
		return this.idpointacces;
	}

	public void setIdpointacces(int idpointacces) {
		this.idpointacces = idpointacces;
	}

	public int getIdfingerprints() {
		return this.idfingerprints;
	}

	public void setIdfingerprints(int idfingerprints) {
		this.idfingerprints = idfingerprints;
	}

	

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpointacces();
		result = 37 * result + this.getIdfingerprints();
		return result;
	}

}
