package com.pfe.localisation.object;

import com.fasterxml.jackson.annotation.JsonIgnore;



// Generated 29 avr. 2014 13:48:35 by Hibernate Tools 3.4.0.CR1

/**
 * Rssi generated by hbm2java
 */
public class Rssi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8456054513310825964L;
	private RssiId id;
	private Fingerprints fingerprints;
	private Pointacces pointacces;
	private float valrssi;

	public Rssi() {
	}

	public Rssi(RssiId id, Fingerprints fingerprints, Pointacces pointacces,
			float valrssi) {
		this.id = id;
		this.fingerprints = fingerprints;
		this.pointacces = pointacces;
		this.valrssi = valrssi;
	}

	public RssiId getId() {
		return this.id;
	}

	public void setId(RssiId id) {
		this.id = id;
	}

	@JsonIgnore
	public Fingerprints getFingerprints() {
		return this.fingerprints;
	}

	public void setFingerprints(Fingerprints fingerprints) {
		this.fingerprints = fingerprints;
	}

	@JsonIgnore
	public Pointacces getPointacces() {
		return this.pointacces;
	}

	public void setPointacces(Pointacces pointacces) {
		this.pointacces = pointacces;
	}

	public float getValrssi() {
		return this.valrssi;
	}

	public void setValrssi(float valrssi) {
		this.valrssi = valrssi;
	}

}
